from pathlib import Path
from smtplib import SMTPRecipientsRefused, SMTPAuthenticationError

import pytest
from jinja2 import Environment, FileSystemLoader, TemplateNotFound

from app.core.config import settings
from app.utils.email_utils import (
    send_email,
    send_new_account_email,
    send_reset_api_key_email,
    jinja_emails_env
)


def test_send_email_wrong_recipient_address() -> None:
    with pytest.raises(Exception) as e:
        send_email("wrong email address", "My test mail subject", "html_template", "text_template")
    assert e.type == SMTPRecipientsRefused


def test_send_email_wrong_host_login_user(mocker) -> None:
    mocker.patch.object(settings, 'EMAILS_FROM_EMAIL', "wrong login user")
    with pytest.raises(Exception) as e:
        send_email(settings.TESTS_EMAIL, "My test mail subject", "html_template", "text_template")
    assert e.type == SMTPAuthenticationError


def test_send_email_wrong_login_smtp_password(mocker) -> None:
    mocker.patch.object(settings, 'SMTP_PASSWORD', "wrong password")
    with pytest.raises(Exception) as e:
        send_email(settings.TESTS_EMAIL, "My test mail subject", "html_template", "text_template")
    assert e.type == SMTPAuthenticationError


def test_send_new_account_email(mocker) -> None:
    no_loader_jinja_env = Environment()
    email_to = settings.TESTS_EMAIL
    data = {
        "project_name": settings.PROJECT_NAME,
        "subject": f"{settings.PROJECT_NAME} - New account for user with email {email_to}",
        "email_to": email_to,
        "link": settings.API_DOCS_LINK
    }
    # reproduce templates directly from file (instead of using Jinja Env. loader as in tested function)
    with open(Path(settings.EMAIL_TEMPLATES_DIR) / 'new_account.html') as html_file:
        html_str = html_file.read()
        html_template = no_loader_jinja_env.from_string(html_str).render(**data)
    with open(Path(settings.EMAIL_TEMPLATES_DIR) / 'new_account.txt') as text_file:
        text_str = text_file.read()
        text_template = no_loader_jinja_env.from_string(text_str).render(**data)

    mock_send_email = mocker.patch('app.utils.email_utils.send_email')
    send_new_account_email(email_to)
    # test if templates generated by Jinja2 in send_new_account_email() and used to call the mocked send_email()
    # are those expected in EMAIL_TEMPLATES_DIR :
    mock_send_email.assert_called_with(settings.TESTS_EMAIL, data["subject"], html_template, text_template)


def test_send_new_account_email_not_existing_template_raises_exception(mocker) -> None:
    mocker.patch.object(jinja_emails_env, 'loader', FileSystemLoader(Path("wrong path")))
    with pytest.raises(Exception) as e:
        send_new_account_email(settings.TESTS_EMAIL)
    assert e.type == TemplateNotFound


def test_send_reset_api_key_email(mocker) -> None:
    no_loader_jinja_env = Environment()
    test_token = "mock_reset_apikey_token"
    email_to = settings.TESTS_EMAIL
    data = {
        "project_name": settings.PROJECT_NAME,
        "subject": f"{settings.PROJECT_NAME} - API Key recovery for user with email {email_to}",
        "email_to": email_to,
        "expire_link_hr": settings.EMAIL_RESET_TOKEN_EXPIRE_HOURS,
        "link": Path(settings.API_LINK) / f"login/reset-api-key-form?email={email_to}&token={test_token}"
    }
    # reproduce templates directly from file (instead of using Jinja Env. loader as in tested function)
    with open(Path(settings.EMAIL_TEMPLATES_DIR) / 'reset_api_key_email.html') as html_file:
        html_str = html_file.read()
        html_template = no_loader_jinja_env.from_string(html_str).render(**data)
    with open(Path(settings.EMAIL_TEMPLATES_DIR) / 'reset_api_key_email.txt') as text_file:
        text_str = text_file.read()
        text_template = no_loader_jinja_env.from_string(text_str).render(**data)

    mock_send_email = mocker.patch('app.utils.email_utils.send_email')
    send_reset_api_key_email(email_to, test_token)
    # test if templates generated by Jinja2 in send_reset_api_key_email() and used to call the mocked send_email()
    # are those expected in EMAIL_TEMPLATES_DIR :
    mock_send_email.assert_called_with(settings.TESTS_EMAIL, data["subject"], html_template, text_template)


def test_send_reset_api_key_email_not_existing_template_raises_exception(mocker) -> None:
    mocker.patch.object(jinja_emails_env, 'loader', FileSystemLoader(Path("wrong path")))
    with pytest.raises(Exception) as e:
        send_reset_api_key_email(settings.TESTS_EMAIL, "reset apikey token")
    assert e.type == TemplateNotFound
