"""first migration

Revision ID: 2890a6d98d15
Revises: 
Create Date: 2021-12-31 19:37:53.451287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2890a6d98d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantstatus_id'), 'participantstatus', ['id'], unique=False)
    op.create_index(op.f('ix_participantstatus_name'), 'participantstatus', ['name'], unique=True)
    op.create_table('participanttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nb_session_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participanttype_id'), 'participanttype', ['id'], unique=False)
    op.create_index(op.f('ix_participanttype_name'), 'participanttype', ['name'], unique=True)
    op.create_index(op.f('ix_participanttype_nb_session_week'), 'participanttype', ['nb_session_week'], unique=False)
    op.create_table('sessionstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessionstatus_id'), 'sessionstatus', ['id'], unique=False)
    op.create_index(op.f('ix_sessionstatus_name'), 'sessionstatus', ['name'], unique=True)
    op.create_table('sessiontype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessiontype_id'), 'sessiontype', ['id'], unique=False)
    op.create_index(op.f('ix_sessiontype_name'), 'sessiontype', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_api_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_id'), 'speaker', ['id'], unique=False)
    op.create_index(op.f('ix_speaker_slot_time'), 'speaker', ['slot_time'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_end_date'), 'availability', ['end_date'], unique=False)
    op.create_index(op.f('ix_availability_id'), 'availability', ['id'], unique=False)
    op.create_index(op.f('ix_availability_speaker_id'), 'availability', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_availability_start_date'), 'availability', ['start_date'], unique=False)
    op.create_index(op.f('ix_availability_time'), 'availability', ['time'], unique=False)
    op.create_index(op.f('ix_availability_week_day'), 'availability', ['week_day'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['participantstatus.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['participanttype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_id'), 'participant', ['id'], unique=False)
    op.create_index(op.f('ix_participant_speaker_id'), 'participant', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_participant_status_id'), 'participant', ['status_id'], unique=False)
    op.create_index(op.f('ix_participant_type_id'), 'participant', ['type_id'], unique=False)
    op.create_table('reservation',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'availability_id')
    )
    op.create_index(op.f('ix_reservation_availability_id'), 'reservation', ['availability_id'], unique=False)
    op.create_index(op.f('ix_reservation_participant_id'), 'reservation', ['participant_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sessionstatus.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['sessiontype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_comments'), 'session', ['comments'], unique=False)
    op.create_index(op.f('ix_session_date'), 'session', ['date'], unique=False)
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_index(op.f('ix_session_participant_id'), 'session', ['participant_id'], unique=False)
    op.create_index(op.f('ix_session_status_id'), 'session', ['status_id'], unique=False)
    op.create_index(op.f('ix_session_time'), 'session', ['time'], unique=False)
    op.create_index(op.f('ix_session_type_id'), 'session', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_type_id'), table_name='session')
    op.drop_index(op.f('ix_session_time'), table_name='session')
    op.drop_index(op.f('ix_session_status_id'), table_name='session')
    op.drop_index(op.f('ix_session_participant_id'), table_name='session')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_index(op.f('ix_session_date'), table_name='session')
    op.drop_index(op.f('ix_session_comments'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_reservation_participant_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_availability_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_participant_type_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_status_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_speaker_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_id'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_availability_week_day'), table_name='availability')
    op.drop_index(op.f('ix_availability_time'), table_name='availability')
    op.drop_index(op.f('ix_availability_start_date'), table_name='availability')
    op.drop_index(op.f('ix_availability_speaker_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_end_date'), table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_speaker_slot_time'), table_name='speaker')
    op.drop_index(op.f('ix_speaker_id'), table_name='speaker')
    op.drop_table('speaker')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sessiontype_name'), table_name='sessiontype')
    op.drop_index(op.f('ix_sessiontype_id'), table_name='sessiontype')
    op.drop_table('sessiontype')
    op.drop_index(op.f('ix_sessionstatus_name'), table_name='sessionstatus')
    op.drop_index(op.f('ix_sessionstatus_id'), table_name='sessionstatus')
    op.drop_table('sessionstatus')
    op.drop_index(op.f('ix_participanttype_nb_session_week'), table_name='participanttype')
    op.drop_index(op.f('ix_participanttype_name'), table_name='participanttype')
    op.drop_index(op.f('ix_participanttype_id'), table_name='participanttype')
    op.drop_table('participanttype')
    op.drop_index(op.f('ix_participantstatus_name'), table_name='participantstatus')
    op.drop_index(op.f('ix_participantstatus_id'), table_name='participantstatus')
    op.drop_table('participantstatus')
    # ### end Alembic commands ###
